config/routes.rb
Boda::Application.routes.draw do

  resources :messages

  root to: "landing#index"

  devise_for :users
  devise_for :administrators
  
  match "/inicio" => "home#index", as: :home
  match "/laboda" => "home#weeding", as: :weeding
  match "/lista_de_regalos" => "home#presents", as: :presents
  match "/mas_info" => "home#about", as: :about
  match "/yovoy" => "home#confirm", as: :confirmation
  match "/entorno" => "home#area", as: :area
  
  get "landing/index"
  post "landing/create_access_request"
  get "home/confirm_guest"
  get "home/cancel_guest"
  put "home/update_guest"
  
  namespace :admin do 
    root to: "main#index"
    
    resources :access_requests do
      member do 
        get :approve
        get :reject
      end
    end
    
    resources :guests 
  end
  
end

app/models/admin/guest.rb
class Admin::Guest < ActiveRecord::Base
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  attr_accessible :city, :has_confirmed, :lastname, :name, :number_of_companions, :user
  
  scope :confirmed, where(:has_confirmed => true)
  scope :not_confirmed, where(:has_confirmed => false)
end

app/controllers/admin/guests_controller.rb
class Admin::GuestsController < Admin::BaseController
  # GET /admin/guests
  # GET /admin/guests.json
  def index
    @admin_guests = Admin::Guest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_guests }
    end
  end

  # GET /admin/guests/1
  # GET /admin/guests/1.json
  def show
    @admin_guest = Admin::Guest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_guest }
    end
  end

  # GET /admin/guests/new
  # GET /admin/guests/new.json
  def new
    @admin_guest = Admin::Guest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_guest }
    end
  end

  # GET /admin/guests/1/edit
  def edit
    @admin_guest = Admin::Guest.find(params[:id])
  end

  # POST /admin/guests
  # POST /admin/guests.json
  def create
    @admin_guest = Admin::Guest.new(params[:admin_guest])

    respond_to do |format|
      if @admin_guest.save
        format.html { redirect_to @admin_guest, notice: 'Guest was successfully created.' }
        format.json { render json: @admin_guest, status: :created, location: @admin_guest }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/guests/1
  # PUT /admin/guests/1.json
  def update
    @admin_guest = Admin::Guest.find(params[:id])

    respond_to do |format|
      if @admin_guest.update_attributes(params[:admin_guest])
        format.html { redirect_to @admin_guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/guests/1
  # DELETE /admin/guests/1.json
  def destroy
    @admin_guest = Admin::Guest.find(params[:id])
    @admin_guest.destroy

    respond_to do |format|
      format.html { redirect_to admin_guests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/views/admin/guests/_form.html.erb
<%= form_for(@admin_guest) do |f| %>
  <% if @admin_guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_guest.errors.count, "error") %> prohibited this admin_guest from being saved:</h2>

      <ul>
      <% @admin_guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :has_confirmed %><br />
    <%= f.check_box :has_confirmed %>
  </div>
  <div class="field">
    <%= f.label :number_of_companions %><br />
    <%= f.number_field :number_of_companions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/guests/edit.html.erb
<h1>Editing admin_guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_guest %> |
<%= link_to 'Back', admin_guests_path %>

app/views/admin/guests/index.html.erb
<h1>Listing admin_guests</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Lastname</th>
    <th>City</th>
    <th>Has confirmed</th>
    <th>Number of companions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_guests.each do |admin_guest| %>
  <tr>
    <td><%= admin_guest.name %></td>
    <td><%= admin_guest.lastname %></td>
    <td><%= admin_guest.city %></td>
    <td><%= admin_guest.has_confirmed %></td>
    <td><%= admin_guest.number_of_companions %></td>
    <td><%= link_to 'Show', admin_guest %></td>
    <td><%= link_to 'Edit', edit_admin_guest_path(admin_guest) %></td>
    <td><%= link_to 'Destroy', admin_guest, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guest', new_admin_guest_path %>

app/views/admin/guests/new.html.erb
<h1>New admin_guest</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_guests_path %>

app/views/admin/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_guest.name %>
</p>

<p>
  <b>Lastname:</b>
  <%= @admin_guest.lastname %>
</p>

<p>
  <b>City:</b>
  <%= @admin_guest.city %>
</p>

<p>
  <b>Has confirmed:</b>
  <%= @admin_guest.has_confirmed %>
</p>

<p>
  <b>Number of companions:</b>
  <%= @admin_guest.number_of_companions %>
</p>


<%= link_to 'Edit', edit_admin_guest_path(@admin_guest) %> |
<%= link_to 'Back', admin_guests_path %>