config/routes.rb
Boda::Application.routes.draw do

  resources :messages

  root to: "landing#index"

  devise_for :users
  devise_for :administrators
  
  match "/inicio" => "home#index", as: :home
  match "/laboda" => "home#weeding", as: :weeding
  match "/lista_de_regalos" => "home#presents", as: :presents
  match "/mas_info" => "home#about", as: :about
  match "/yovoy" => "home#confirm", as: :confirmation
  match "/entorno" => "home#area", as: :area
  
  get "landing/index"
  post "landing/create_access_request"
  get "home/confirm_guest"
  get "home/cancel_guest"
  put "home/update_guest"
  
  namespace :admin do 
    root to: "main#index"
    
    resources :access_requests do
      member do 
        get :approve
        get :reject
      end
    end
    
    resources :guests 
  end
  
end

app/controllers/home_controller.rb
#encoding: UTF-8
class HomeController < BaseController
  def index
  end

  def confirm
    @guest = Admin::Guest.find_by_user_id(current_user.id)
  end

  def weeding
  end

  def presents
  end
  
  def area
  end
  
  def about
  end
  
  def confirm_guest
    @admin_guest = Admin::Guest.find(params[:id])

    respond_to do |format|
      if @admin_guest.update_attribute(:has_confirmed, true)
        format.html { redirect_to confirmation_path, notice: 'Gracias. Acabas de confirmar tu asistencia a la boda. Recuerda indicar el número de acompañantes.' }
        format.json { head :no_content }
      else
        format.html { redirect_to confirmation_path, notice: 'No hemos podido confirmar tu asistencia. Si el problema persiste ponte en contacto con nosotros.' }
        format.json { render json: @admin_guest.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def cancel_guest
    @admin_guest = Admin::Guest.find(params[:id])

    respond_to do |format|
      if @admin_guest.update_attribute(:has_confirmed, false)
        format.html { redirect_to confirmation_path, notice: 'Es una pena oir eso :( Espramos que al final puedas asistir.' }
        format.json { head :no_content }
      else
        format.html { redirect_to confirmation_path, notice: 'No hemos podido confirmar tu asistencia. Si persiste ponte en contacto con nosotros.' }
        format.json { render json: @admin_guest.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_guest
    @admin_guest = Admin::Guest.find(params[:id])

    respond_to do |format|
      if @admin_guest.update_attributes(params[:admin_guest])
        format.html { redirect_to confirmation_path, notice: 'Tu información se ha actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { redirect_to confirmation_path, notice: 'Se ha producido un error.' }
        format.json { render json: @admin_guest.errors, status: :unprocessable_entity }
      end
    end
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="row">
  <h1>Os atenderemos encantados</h1>
  <div class="six columns">
    <h3>Déborah Silva</h3>
    <div class="box">
      <p class="info">
        <b>tlf.</b> 680 85 33 25<br />
        <b>email.</b> deborahsilvavarela@hotmail.com<br />      
      </p>
    </div>
  </div>
  <div class="six columns">
    <h3>Pablo Formoso</h3>
    <div class="box">
      <p class="info">
        <b>tlf.</b> 670 71 14 40<br />
        <b>email.</b> pablo@pabloformoso.com<br />      
      </p>
    </div>
  </div>
</div>
  

app/views/home/area.html.erb
<div class="row">
  <h1>Estamos trabajando en esta parte</h1>
</div>

app/views/home/confirm.html.erb
<div class="row">
  <h3>Hola, <%= @guest.name %></h3>
  <div class="six columns box">
    <% if !@guest.has_confirmed %>
    <p class="info">
      Aun no has confirmado tu asistencia. Pulsa él siguiente botón para confirmar la asistencia. 
      <br />
      <%= link_to "Confirmar Asistencia", home_confirm_guest_path(id: @guest.id), :class => "medium radius success button" %>
      <br />
      De cara a la organización del evento es importante que confirmes tu asistencia lo antes posible.
    </p>
    <% else %>
      <p class="info">
        Gracias. Ya has confirmado la asistencia.
        <br />
        Sin por algún motivo ya no vas a poder asistir, muy a nuestros pesar, puedes usar el siguiente botón para anular tu asistencia.<br />
        <%= link_to "Cancelar Asistencia", home_cancel_guest_path(id: @guest.id), :class => "medium radius alert button" %>
      </p>
    <% end %>  
  </div>

  <div class="five columns offset-by-one box">
    <p class="info">
      Completa o modifica tus datos:
      <%= form_for @guest, :url => home_update_guest_path(id: @guest.id) do |f| %>
        <% if @guest.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@admin_guest.errors.count, "error") %> prohibited this admin_guest from being saved:</h2>
            <ul>
            <% @admin_guest.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

          <%= f.label :name, "Nombre" %>
          <%= f.text_field :name %>


          <%= f.label :city, "Ciudad" %>
          <%= f.text_field :city %>

          <%= f.label :number_of_companions, "Número de acompañantes" %>
          <%= f.number_field :number_of_companions %>

        <div class="actions">
          <%= f.submit "Actualizar", :disable_with => 'Actualizando...', :class => "medium radius button right" %>
        </div>
      <% end %>
    </p>
  </div>

</div>

app/views/home/index.html.erb
<div class="row">
  <div class="six columns box">
    <p class="info">
      Gracias por estar aquí :)<br />
      En esta página podrás confirmar tu asistencia a la boda, agregar los datos de acompañante/s, conocer los horarios, toda la información del hotel etc... poco a poco iremos colgando algunas sorpresas, fotos de los preparativos. También podréis acceder a la lista de bodas en Zankyou, una forma fácil de escoger los regalos sin moverte de casa.
      <br />
      No dudéis en poneros en contacto con nosotros.
    </p>
  </div>
  
  <div class="six columns">
    <div id="featured">
      <%= image_tag "img2.jpg" %>
      <%= image_tag "img3.jpg" %>
      <%= image_tag "img4.jpg" %>
      <%= image_tag "img5.jpg" %>
      <%= image_tag "img6.jpg" %>      
    </div>
  </div>
</div>

app/views/home/presents.html.erb
<h1>Home#presents</h1>
<p>Find me in app/views/home/presents.html.erb</p>

app/views/home/weeding.html.erb
<div class="row">
  <h3>12:30 - La Ceremonia</h3>
  <div class="eight columns box">
    <p class="info">
      La ceremonia tendrá lugar en la Parroquia de Santa Eulalia de Lians, en Oleiros.
      Dada la cercanía al hotel (aprox. 1 kilómetro) lo idóneo sería partir desde el Hotel Portocobo para minimizar en número de vehículos desplazados.<br />
      La iglesia se encuentra en la Calle Camino del Parque, Oleiros, por la carretera AC-8510. El acceso recomendado es desde la carretera de Santa Cruz.
    </p>  
  </div>
  <div class="four columns">
    <iframe width="303" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.es/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=Cami%C3%B1o+do+Parque+1,+Oleiros&amp;aq=t&amp;sll=41.78587,2.36213&amp;sspn=1.736665,4.22699&amp;t=h&amp;ie=UTF8&amp;hq=&amp;hnear=Camino+del+Parque,+15993+Oleiros,+A+Coru%C3%B1a,+Galicia&amp;z=14&amp;ll=43.332449,-8.351729&amp;output=embed"></iframe>
  </div>
</div>

<div class="row">
  <h3>13:05 - Fin de la Ceremonia, fotos de exterior</h3>
  <div class="eight columns box">
    <p class="info">
      En este tiempo los novios haremos fotos en los exteriores y con los invitados. Los que así lo deseen pueden desplazarse al Hotel.
      Lo que decidan ir caminando podrán volver al hotel en un trayecto de 20 min bastante agradable si el tiempo nos acompaña.
    </p>
  </div>
  <div class="four columns">

    <div id="featured">
      <%= image_tag "lians1.jpg" %>
      <%= image_tag "lians2.jpg" %>
      <%= image_tag "lians3.jpg" %>
    </div>
  </div>
</div>

<div class="row">
  <h3>14:00 - Aperitivos y comida</h3>
  <div class="eight columns box">
    <p class="info">
      Darán comienzo los aperitivos en el Hotel Portocobo, con una duración aproximada de una hora. Si la climatología nos acompaña se realizará en los exteriores del hotel disfrutando de las vistas que nos brinda. Acto seguido pasaremos a el salón principal para comenzar la comida. Intentaremos que esta sea lo más amena posible para todos.
    </p>
  </div>
  <div class="four columns">
    <%= image_tag "hotel1.jpg", :title => "Portocobo" %>
  </div>
</div>

<div class="row">
  <h3>17:30 - Fiesta y más fiesta</h3>
  <div class="eight columns box">
    <p class="info">
      A partir de esta hora pasaremos a El Baile, la barra libre y la fiesta de verdad. Tendremos dos zonas, en la zona del banquete se pondrá una selección de música tranquila de los 70s, 80s y 90s para tomar unas copas y mantener una conversación tranquila (o los que quieran arreglar el país, adelante); pegado al salón del banquete tenemos la discoteca donde se servirá otra barra libre y la música para que todos bailemos con una sorpresa final :)
    </p>
  </div>
  <div class="four columns">
    <%= image_tag "disco1.jpg", :title => "Portocobo" %>
  </div>
</div>