config/routes.rb
Boda::Application.routes.draw do

  resources :messages

  root to: "landing#index"

  devise_for :users
  devise_for :administrators
  
  match "/inicio" => "home#index", as: :home
  match "/laboda" => "home#weeding", as: :weeding
  match "/lista_de_regalos" => "home#presents", as: :presents
  match "/mas_info" => "home#about", as: :about
  match "/yovoy" => "home#confirm", as: :confirmation
  match "/entorno" => "home#area", as: :area
  
  get "landing/index"
  post "landing/create_access_request"
  get "home/confirm_guest"
  get "home/cancel_guest"
  put "home/update_guest"
  
  namespace :admin do 
    root to: "main#index"
    
    resources :access_requests do
      member do 
        get :approve
        get :reject
      end
    end
    
    resources :guests 
  end
  
end

app/models/admin/access_request.rb
class Admin::AccessRequest < ActiveRecord::Base

  attr_accessible :email, :name, :revised
  
  scope :not_revised, where(:revised => false) 
end

app/controllers/admin/access_requests_controller.rb
class Admin::AccessRequestsController < Admin::BaseController
  
  # GET /admin/access_requests
  # GET /admin/access_requests.json
  def index
    @admin_access_requests = Admin::AccessRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_access_requests }
    end
  end

  # GET /admin/access_requests/1
  # GET /admin/access_requests/1.json
  def show
    @admin_access_request = Admin::AccessRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_access_request }
    end
  end

  # GET /admin/access_requests/new
  # GET /admin/access_requests/new.json
  def new
    @admin_access_request = Admin::AccessRequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_access_request }
    end
  end

  # GET /admin/access_requests/1/edit
  def edit
    @admin_access_request = Admin::AccessRequest.find(params[:id])
  end

  # POST /admin/access_requests
  # POST /admin/access_requests.json
  def create
    @admin_access_request = Admin::AccessRequest.new(params[:admin_access_request])

    respond_to do |format|
      if @admin_access_request.save
        
        AccessRequestMailer.request_received(@admin_access_request).deliver
        
        format.html { redirect_to @admin_access_request, notice: 'Access request was successfully created.' }
        format.json { render json: @admin_access_request, status: :created, location: @admin_access_request }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_access_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/access_requests/1
  # PUT /admin/access_requests/1.json
  def update
    @admin_access_request = Admin::AccessRequest.find(params[:id])

    respond_to do |format|
      if @admin_access_request.update_attributes(params[:admin_access_request])
        format.html { redirect_to @admin_access_request, notice: 'Access request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_access_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/access_requests/1
  # DELETE /admin/access_requests/1.json
  def destroy
    @admin_access_request = Admin::AccessRequest.find(params[:id])
    @admin_access_request.destroy

    respond_to do |format|
      format.html { redirect_to admin_access_requests_url }
      format.json { head :no_content }
    end
  end
  
  def approve 
    @admin_access_request = Admin::AccessRequest.find(params[:id])
    @user = User.create!(:email => @admin_access_request.email, :password => "boda2012", :password_confirmation => "boda2012")
    if @user
      @guest = Admin::Guest.create(:name => @admin_access_request.name, :user => @user, :has_confirmed => false, :main => true, :number_of_companions => 0)
      @admin_access_request.update_attribute(:revised, true)
      AccessRequestMailer.accept_request(@admin_access_request).deliver
      redirect_to admin_root_path, notice: "Invitado creado"
    else
      redirect_to admin_root_path, notice: "Error al crear el invitado"
    end
  end
  
  def reject
    @admin_access_request = Admin::AccessRequest.find(params[:id])
    @admin_access_request.destroy
    redirect_to admin_root_path, notice: "Solicitud rechazada"
  end
end

app/helpers/admin/access_requests_helper.rb
module Admin::AccessRequestsHelper
end

app/views/admin/access_requests/_form.html.erb
<%= form_for(@admin_access_request) do |f| %>
  <% if @admin_access_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_access_request.errors.count, "error") %> prohibited this admin_access_request from being saved:</h2>

      <ul>
      <% @admin_access_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :revised %><br />
    <%= f.check_box :revised %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/access_requests/edit.html.erb
<h1>Editing admin_access_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_access_request %> |
<%= link_to 'Back', admin_access_requests_path %>

app/views/admin/access_requests/index.html.erb
<h1>Listing admin_access_requests</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Revised</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_access_requests.each do |admin_access_request| %>
  <tr>
    <td><%= admin_access_request.name %></td>
    <td><%= admin_access_request.email %></td>
    <td><%= admin_access_request.revised %></td>
    <td><%= link_to 'Show', admin_access_request %></td>
    <td><%= link_to 'Edit', edit_admin_access_request_path(admin_access_request) %></td>
    <td><%= link_to 'Destroy', admin_access_request, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Access request', new_admin_access_request_path %>

app/views/admin/access_requests/new.html.erb
<h1>New admin_access_request</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_access_requests_path %>

app/views/admin/access_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_access_request.name %>
</p>

<p>
  <b>Email:</b>
  <%= @admin_access_request.email %>
</p>

<p>
  <b>Revised:</b>
  <%= @admin_access_request.revised %>
</p>


<%= link_to 'Edit', edit_admin_access_request_path(@admin_access_request) %> |
<%= link_to 'Back', admin_access_requests_path %>