config/routes.rb
Boda::Application.routes.draw do

  resources :messages

  root to: "landing#index"

  devise_for :users
  devise_for :administrators
  
  match "/inicio" => "home#index", as: :home
  match "/laboda" => "home#weeding", as: :weeding
  match "/lista_de_regalos" => "home#presents", as: :presents
  match "/mas_info" => "home#about", as: :about
  match "/yovoy" => "home#confirm", as: :confirmation
  match "/entorno" => "home#area", as: :area
  
  get "landing/index"
  post "landing/create_access_request"
  get "home/confirm_guest"
  get "home/cancel_guest"
  put "home/update_guest"
  
  namespace :admin do 
    root to: "main#index"
    
    resources :access_requests do
      member do 
        get :approve
        get :reject
      end
    end
    
    resources :guests 
  end
  
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/access_request.rb
class Admin::AccessRequest < ActiveRecord::Base

  attr_accessible :email, :name, :revised
  
  scope :not_revised, where(:revised => false) 
end

app/models/admin/guest.rb
class Admin::Guest < ActiveRecord::Base
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  attr_accessible :city, :has_confirmed, :lastname, :name, :number_of_companions, :user
  
  scope :confirmed, where(:has_confirmed => true)
  scope :not_confirmed, where(:has_confirmed => false)
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :guest, :class_name => "Admin::Guest", :foreign_key => "guest_id"
  attr_accessible :content
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :guests, :class_name => "Admin::Guest"
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin/application'
  before_filter :authenticate_administrator!
end

app/controllers/admin/main_controller.rb
class Admin::MainController < Admin::BaseController
  
  def index
    @access_requests = Admin::AccessRequest.not_revised
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  layout "user"
  before_filter :authenticate_user!, :days
  
  def days
    a = Time.gm(2012,12,01)
    b = Time.now
    
    @days = (a - b).to_i / (24 * 60 * 60)
  end
  
end

app/controllers/home_controller.rb
#encoding: UTF-8
class HomeController < BaseController
  def index
  end

  def confirm
    @guest = Admin::Guest.find_by_user_id(current_user.id)
  end

  def weeding
  end

  def presents
  end
  
  def area
  end
  
  def about
  end
  
  def confirm_guest
    @admin_guest = Admin::Guest.find(params[:id])

    respond_to do |format|
      if @admin_guest.update_attribute(:has_confirmed, true)
        format.html { redirect_to confirmation_path, notice: 'Gracias. Acabas de confirmar tu asistencia a la boda. Recuerda indicar el número de acompañantes.' }
        format.json { head :no_content }
      else
        format.html { redirect_to confirmation_path, notice: 'No hemos podido confirmar tu asistencia. Si el problema persiste ponte en contacto con nosotros.' }
        format.json { render json: @admin_guest.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def cancel_guest
    @admin_guest = Admin::Guest.find(params[:id])

    respond_to do |format|
      if @admin_guest.update_attribute(:has_confirmed, false)
        format.html { redirect_to confirmation_path, notice: 'Es una pena oir eso :( Espramos que al final puedas asistir.' }
        format.json { head :no_content }
      else
        format.html { redirect_to confirmation_path, notice: 'No hemos podido confirmar tu asistencia. Si persiste ponte en contacto con nosotros.' }
        format.json { render json: @admin_guest.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_guest
    @admin_guest = Admin::Guest.find(params[:id])

    respond_to do |format|
      if @admin_guest.update_attributes(params[:admin_guest])
        format.html { redirect_to confirmation_path, notice: 'Tu información se ha actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { redirect_to confirmation_path, notice: 'Se ha producido un error.' }
        format.json { render json: @admin_guest.errors, status: :unprocessable_entity }
      end
    end
    
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @access_request = Admin::AccessRequest.new
    @user = User.new
    if current_user
      redirect_to home_path
    end
  end
  
  def create_access_request
    @admin_access_request = Admin::AccessRequest.new(params[:admin_access_request])

    respond_to do |format|
      if @admin_access_request.save
        
        AccessRequestMailer.request_received(@admin_access_request).deliver
        
        format.html { redirect_to root_path, notice: 'Solicitud recibida correctamente.' }
        format.json { render json: @admin_access_request, status: :created, location: @admin_access_request }
      else
        format.html { render action: "index" }
        format.json { render json: @admin_access_request.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < BaseController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])
    @message.guest_id = current_user.guests.first.id
    
    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Gracias por escribir en nuestro libro :)' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/helpers/admin/main_helper.rb
module Admin::MainHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boda de Déborah y Pablo :: 1 de Diciembre 2012</title>
  <%= stylesheet_link_tag    "admin/application", :media => "all" %>
  <%= javascript_include_tag "admin/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
  <div id="myModal" class="reveal-modal small">
    <h3><%= flash[:notice] %></h3>
    <a class="close-reveal-modal">&#215;</a>
  </div>
  <script type="text/javascript">$('#myModal').reveal();</script>
<% end %>
  
<div class="row">
  <%= yield %>
</div>
  

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boda de Déborah y Pablo :: 1 de Diciembre 2012</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  
<%= yield %>

</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boda de Déborah y Pablo :: 1 de Diciembre 2012</title>
  <%= stylesheet_link_tag    "users/application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<% if flash[:notice] %>
  <div id="myModal" class="reveal-modal small">
    <h3><%= flash[:notice] %></h3>
    <a class="close-reveal-modal">&#215;</a>
  </div>
  <script type="text/javascript">$('#myModal').reveal();</script>
<% end %>

<div class="row">
  <div class="eight columns">
    <h1>Deborah y Pablo</h1>  
  </div>
  <div class="four columns">
    <h3>Quedan: <%= @days %> <%= @days == 1 ? "día" : "días" %></h3>
    <%= link_to "[X] Salir".html_safe, destroy_user_session_path, :method => :delete %>
  </div>
</div>
<div class="row">
  <ul class="nav-bar">
    <li><%= link_to "Inicio", home_path %></li>
    <li><%= link_to "La Boda", weeding_path %></li>
    <li><%= link_to "Lista de Regalos", "http://pabloydeborah.zankyou.com/es", target: :blank %>
    <li><%= link_to "Confirmar Asistencia", confirmation_path %></li>
    <li><%= link_to "Libro de Visitas", messages_path %></li>
    <li><%= link_to "Entorno y Estancia", area_path %></li>
    <li><%= link_to "Contacto", about_path %></li>
  </ul>
</div>


<%= yield %>
<br /><br />
<div class="row centered">
  <div class="twelve colums centered">
    <p class="footer">
      Softwhisper Dev ®
    </p>
  </div>
</div>
</body>
</html>